#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
%define keepstatic 1
Name     : glslang
Version  : 12.2.0
Release  : 44
URL      : https://github.com/KhronosGroup/glslang/archive/12.2.0/glslang-12.2.0.tar.gz
Source0  : https://github.com/KhronosGroup/glslang/archive/12.2.0/glslang-12.2.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : AML Apache-2.0 BSD-3-Clause
Requires: glslang-bin = %{version}-%{release}
Requires: glslang-lib = %{version}-%{release}
Requires: glslang-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-cmake
BuildRequires : flex
BuildRequires : glibc-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# News
1. [As discussed in #3107](https://github.com/KhronosGroup/glslang/issues/3107), the default branch of this repository is now 'main'. This change should be transparent to repository users, since github rewrites many references to the old 'master' branch to 'main'. However, if you have a checked-out local clone, you may wish to take the following steps as recommended by github:

%package bin
Summary: bin components for the glslang package.
Group: Binaries
Requires: glslang-license = %{version}-%{release}

%description bin
bin components for the glslang package.


%package dev
Summary: dev components for the glslang package.
Group: Development
Requires: glslang-lib = %{version}-%{release}
Requires: glslang-bin = %{version}-%{release}
Provides: glslang-devel = %{version}-%{release}
Requires: glslang = %{version}-%{release}

%description dev
dev components for the glslang package.


%package lib
Summary: lib components for the glslang package.
Group: Libraries
Requires: glslang-license = %{version}-%{release}

%description lib
lib components for the glslang package.


%package license
Summary: license components for the glslang package.
Group: Default

%description license
license components for the glslang package.


%prep
%setup -q -n glslang-12.2.0
cd %{_builddir}/glslang-12.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685510083
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake .. -DCMAKE_INSTALL_LIBDIR=lib64 \
-DENABLE_GLSLANG_INSTALL=True
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export CFLAGS="$CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake .. -DCMAKE_INSTALL_LIBDIR=lib64 \
-DENABLE_GLSLANG_INSTALL=True
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1685510083
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/glslang
cp %{_builddir}/glslang-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/glslang/f77668fa8c7bb3dc2788af730150c401bd723fed || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/glslangValidator
/V3/usr/bin/spirv-remap
/usr/bin/glslangValidator
/usr/bin/spirv-remap

%files dev
%defattr(-,root,root,-)
/usr/include/glslang/HLSL/hlslAttributes.h
/usr/include/glslang/HLSL/hlslGrammar.h
/usr/include/glslang/HLSL/hlslOpMap.h
/usr/include/glslang/HLSL/hlslParseHelper.h
/usr/include/glslang/HLSL/hlslParseables.h
/usr/include/glslang/HLSL/hlslScanContext.h
/usr/include/glslang/HLSL/hlslTokenStream.h
/usr/include/glslang/HLSL/hlslTokens.h
/usr/include/glslang/Include/BaseTypes.h
/usr/include/glslang/Include/Common.h
/usr/include/glslang/Include/ConstantUnion.h
/usr/include/glslang/Include/InfoSink.h
/usr/include/glslang/Include/InitializeGlobals.h
/usr/include/glslang/Include/PoolAlloc.h
/usr/include/glslang/Include/ResourceLimits.h
/usr/include/glslang/Include/ShHandle.h
/usr/include/glslang/Include/SpirvIntrinsics.h
/usr/include/glslang/Include/Types.h
/usr/include/glslang/Include/arrays.h
/usr/include/glslang/Include/glslang_c_interface.h
/usr/include/glslang/Include/glslang_c_shader_types.h
/usr/include/glslang/Include/intermediate.h
/usr/include/glslang/MachineIndependent/Initialize.h
/usr/include/glslang/MachineIndependent/LiveTraverser.h
/usr/include/glslang/MachineIndependent/ParseHelper.h
/usr/include/glslang/MachineIndependent/RemoveTree.h
/usr/include/glslang/MachineIndependent/Scan.h
/usr/include/glslang/MachineIndependent/ScanContext.h
/usr/include/glslang/MachineIndependent/SymbolTable.h
/usr/include/glslang/MachineIndependent/Versions.h
/usr/include/glslang/MachineIndependent/attribute.h
/usr/include/glslang/MachineIndependent/gl_types.h
/usr/include/glslang/MachineIndependent/glslang_tab.cpp.h
/usr/include/glslang/MachineIndependent/iomapper.h
/usr/include/glslang/MachineIndependent/localintermediate.h
/usr/include/glslang/MachineIndependent/parseVersions.h
/usr/include/glslang/MachineIndependent/preprocessor/PpContext.h
/usr/include/glslang/MachineIndependent/preprocessor/PpTokens.h
/usr/include/glslang/MachineIndependent/propagateNoContraction.h
/usr/include/glslang/MachineIndependent/reflection.h
/usr/include/glslang/Public/ResourceLimits.h
/usr/include/glslang/Public/ShaderLang.h
/usr/include/glslang/Public/resource_limits_c.h
/usr/include/glslang/SPIRV/GLSL.ext.AMD.h
/usr/include/glslang/SPIRV/GLSL.ext.ARM.h
/usr/include/glslang/SPIRV/GLSL.ext.EXT.h
/usr/include/glslang/SPIRV/GLSL.ext.KHR.h
/usr/include/glslang/SPIRV/GLSL.ext.NV.h
/usr/include/glslang/SPIRV/GLSL.std.450.h
/usr/include/glslang/SPIRV/GlslangToSpv.h
/usr/include/glslang/SPIRV/Logger.h
/usr/include/glslang/SPIRV/NonSemanticDebugPrintf.h
/usr/include/glslang/SPIRV/NonSemanticShaderDebugInfo100.h
/usr/include/glslang/SPIRV/SPVRemapper.h
/usr/include/glslang/SPIRV/SpvBuilder.h
/usr/include/glslang/SPIRV/SpvTools.h
/usr/include/glslang/SPIRV/bitutils.h
/usr/include/glslang/SPIRV/disassemble.h
/usr/include/glslang/SPIRV/doc.h
/usr/include/glslang/SPIRV/hex_float.h
/usr/include/glslang/SPIRV/spirv.hpp
/usr/include/glslang/SPIRV/spvIR.h
/usr/include/glslang/build_info.h
/usr/lib64/cmake/HLSLTargets.cmake
/usr/lib64/cmake/SPIRVTargets.cmake
/usr/lib64/cmake/SPVRemapperTargets.cmake
/usr/lib64/cmake/glslang-default-resource-limitsTargets.cmake
/usr/lib64/cmake/glslang/glslang-config-version.cmake
/usr/lib64/cmake/glslang/glslang-config.cmake
/usr/lib64/cmake/glslang/glslang-targets-relwithdebinfo.cmake
/usr/lib64/cmake/glslang/glslang-targets.cmake
/usr/lib64/cmake/glslangValidatorTargets.cmake
/usr/lib64/cmake/spirv-remapTargets.cmake

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libHLSL.so.12.2.0
/V3/usr/lib64/libSPIRV.so.12.2.0
/V3/usr/lib64/libSPVRemapper.so.12.2.0
/V3/usr/lib64/libglslang-default-resource-limits.so.12.2.0
/V3/usr/lib64/libglslang.so.12.2.0
/usr/lib64/libHLSL.so
/usr/lib64/libHLSL.so.12
/usr/lib64/libHLSL.so.12.2.0
/usr/lib64/libSPIRV.so
/usr/lib64/libSPIRV.so.12
/usr/lib64/libSPIRV.so.12.2.0
/usr/lib64/libSPVRemapper.so
/usr/lib64/libSPVRemapper.so.12
/usr/lib64/libSPVRemapper.so.12.2.0
/usr/lib64/libglslang-default-resource-limits.so
/usr/lib64/libglslang-default-resource-limits.so.12
/usr/lib64/libglslang-default-resource-limits.so.12.2.0
/usr/lib64/libglslang.so
/usr/lib64/libglslang.so.12
/usr/lib64/libglslang.so.12.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/glslang/f77668fa8c7bb3dc2788af730150c401bd723fed
